development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: prelaunchr_development
  password:
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: prelaunchr_test
  password:
production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: prelaunchr_production
  password:

